#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kcausse <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/02/14 17:26:57 by kcausse           #+#    #+#              #
#    Updated: 2018/02/14 17:27:27 by kcausse          ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME = ex09

all: $(NAME)

$(NAME):
	gcc -Wall -Wextra -Werror -Iincludes sources/*.c -o ft_advanced_do-op

clean:
	/bin/rm -f ft_advanced_do-op
